env_defaults: &env_defaults
  working_directory: ~
  docker:
    - image: cimg/node:16.10.0

version: 2.1
jobs:
  prepare:
    <<: *env_defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.0-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1.0-dependencies-

      - node/install-packages:
          pkg-manager: yarn

      - run: yarn install

      - run: yarn add jest-junit -W

      - save_cache:
          paths:
            - node_modules
          key: v1.0-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: yarn run test --ci 
          name: Run Tests
  build:
    <<: *env_defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: yarn run build
          name: Build Typescript Package

orbs:
  node: circleci/node@4.1.0
workflows:
  test:
    jobs:
      - prepare
      - build:
          requires:
            - prepare
      - test:
          requires:
            - build



