type CityListener = {
  code2: string;
  listeners: number;
  name: string;
};
type ArtistRank = {
  sp_popularity_rank: number;
  deezer_fans_rank: number;
  sp_followers_rank: number;
  sp_monthly_listeners_rank: number;
  ins_followers_rank: number;
  ycs_subscribers_rank: number;
  ycs_views_rank: number;
  tiktok_followers_rank: number;
  tiktok_track_posts_rank: number;
  tiktok_likes_rank: number;
  tiktok_top_video_views_rank: number;
  line_music_artist_likes_rank: number;
  line_music_likes_rank: number;
  line_music_plays_rank: number;
  line_music_mv_plays_rank: number;
  melon_artist_fans_rank: number;
  melon_likes_rank: number;
  melon_video_likes_rank: number;
  melon_video_views_rank: number;
  youtube_daily_video_views_rank: number;
  youtube_monthly_video_views_rank: number;
  twitch_followers_rank: number;
  twitch_views_rank: number;
  twitch_monthly_viewer_hours_rank: number;
  twitch_weekly_viewer_hours_rank: number;
  pandora_listeners_28_day_rank: number;
  pandora_lifetime_stations_added_rank: number;
  pandora_lifetime_streams_rank: number;
  boomplay_ranking_current_rank: number;
  boomplay_favorites_rank: number;
  boomplay_shares_rank: number;
  boomplay_comments_rank: number;
  boomplay_plays_rank: number;
};
type CountryRank = {
  code2: string;
  country: string;
  rank: number;
  percentile: number;
};

type GenreRank = {
  code2: string;
  country: string;
  rank: number;
  percentile: number;
  id: number;
  name: string;
  link_type: string;
  score: number;
};
type CMStat = {
  countryRank: CountryRank;
  genreRank: GenreRank;
  secondaryGenreRanks: GenreRank[];
  sp_where_people_listen: CityListener[];
  sp_followers: number;
  deezer_fans: number;
  sp_popularity: number;
  sp_monthly_listeners: number;
  ins_followers: number;
  ycs_subscribers: number;
  ycs_views: number;
  tiktok_followers: number;
  tiktok_likes: number;
  tiktok_top_video_views: number;
  tiktok_track_posts: number;
  line_music_artist_likes: number;
  line_music_likes: number;
  line_music_plays: number;
  line_music_mv_plays: number;
  melon_artist_fans: number;
  melon_likes: number;
  melon_video_likes: number;
  melon_video_views: number;
  youtube_daily_video_views: number;
  youtube_monthly_video_views: number;
  twitch_followers: number;
  twitch_views: number;
  twitch_monthly_viewer_hours: number;
  twitch_weekly_viewer_hours: number;
  pandora_listeners_28_day: number;
  pandora_lifetime_stations_added: number;
  pandora_lifetime_streams: number;
  boomplay_ranking_current: number;
  boomplay_favorites: number;
  boomplay_shares: number;
  boomplay_comments: number;
  boomplay_plays: number;
  num_sp_editorial_playlists: number;
  num_sp_playlists: number;
  sp_playlist_total_reach: number;
  sp_editorial_playlist_total_reach: number;
  num_am_editorial_playlists: number;
  num_am_playlists: number;
  num_de_editorial_playlists: number;
  num_de_playlists: number;
  de_playlist_total_reach: number;
  de_editorial_playlist_total_reach: number;
  num_az_editorial_playlists: number;
  num_az_playlists: number;
  num_yt_editorial_playlists: number;
  num_yt_playlists: number;
  yt_playlist_total_reach: number;
  yt_editorial_playlist_total_reach: number;
  shazam_count: number;
  genius_pageviews: number;
  cm_artist_rank: number;
  cm_artist_rank_percentile: number;
  fan_base_rank: number;
  fan_base_rank_percentile: number;
  engagement_rank: number;
  engagement_rank_percentile: number;
  artist_score: number;
};
export type ArtistCMStatData = {
  obj: CMStat & ArtistRank & {
    timestamp: string;
    weekly_diff: CMStat;
    weekly_diff_percent: CMStat;
    monthly_diff: CMStat;
    monthly_diff_percent: CMStat;
    bimonthly_diff: CMStat;
    bimonthly_diff_percent: CMStat;
  };
};
